# Generated by Django 4.1.2 on 2022-10-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
