# Generated by Django 4.1.2 on 2022-10-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_course_credit_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thirdExaminer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdExaminer', to='root.faculty'),
        ),
    ]
