# Generated by Django 4.1.2 on 2022-10-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_course_duration_coursebill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='external',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external', to='root.faculty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='internal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal', to='root.faculty'),
        ),
    ]
