# Generated by Django 4.1.2 on 2022-10-17 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_alter_course_external_alter_course_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='vivaExternal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.external'),
        ),
    ]
