# Generated by Django 4.1.1 on 2023-03-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_alter_faculty_email_thesispaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNo', models.IntegerField(default=0)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.course')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.faculty')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.semester')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.session')),
            ],
        ),
    ]
